//------------------------------------------------------------------------
// Copyright(c) 2025 Dadou.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Circulate.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Circulate VST3 (64Bit)"
#else
#define stringFileDescription	"Circulate VST3"
#endif
#define stringCompanyName		"13Sounds\0"
#define stringLegalCopyright	"Copyright(c) 2025 Anis Dadou."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
